# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: gitm.proto for package 'gitm.protobuf'

require 'grpc'
require 'gitm_pb'

module Gitm
  module Protobuf
    module Log
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'gitm.protobuf.Log'

        rpc :get, LogRequest, Commit
      end

      Stub = Service.rpc_stub_class
    end
  end
end
