// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Commit struct {
	Object  *Object   `json:"object"`
	Parents []*Object `json:"parents"`
}

type CommitInput struct {
	Object  *ObjectInput   `json:"object"`
	Parents []*ObjectInput `json:"parents"`
}

type LogIterator struct {
	Repository *Repository `json:"repository"`
	Pointers   []*Object   `json:"pointers"`
	Commits    []*Commit   `json:"commits"`
	Num        int         `json:"num"`
}

type LogIteratorInput struct {
	Repository *RepositoryInput `json:"repository"`
	Pointers   []*ObjectInput   `json:"pointers"`
	Commits    []*CommitInput   `json:"commits"`
	Num        *int             `json:"num"`
}

type Object struct {
	Hash string `json:"hash"`
}

type ObjectInput struct {
	Hash *string `json:"hash"`
}

type Repository struct {
	Path string `json:"path"`
}

type RepositoryInput struct {
	Path *string `json:"path"`
}
