// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/gitm.proto

package gitm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Object struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd2cb2805ec62ec, []int{0}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Repository struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd2cb2805ec62ec, []int{1}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Commit struct {
	Object               *Object   `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Parents              []*Object `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd2cb2805ec62ec, []int{2}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *Commit) GetParents() []*Object {
	if m != nil {
		return m.Parents
	}
	return nil
}

type LogIterator struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Pointers             []*Object   `protobuf:"bytes,2,rep,name=pointers,proto3" json:"pointers,omitempty"`
	Commits              []*Commit   `protobuf:"bytes,3,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LogIterator) Reset()         { *m = LogIterator{} }
func (m *LogIterator) String() string { return proto.CompactTextString(m) }
func (*LogIterator) ProtoMessage()    {}
func (*LogIterator) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd2cb2805ec62ec, []int{3}
}

func (m *LogIterator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogIterator.Unmarshal(m, b)
}
func (m *LogIterator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogIterator.Marshal(b, m, deterministic)
}
func (m *LogIterator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogIterator.Merge(m, src)
}
func (m *LogIterator) XXX_Size() int {
	return xxx_messageInfo_LogIterator.Size(m)
}
func (m *LogIterator) XXX_DiscardUnknown() {
	xxx_messageInfo_LogIterator.DiscardUnknown(m)
}

var xxx_messageInfo_LogIterator proto.InternalMessageInfo

func (m *LogIterator) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *LogIterator) GetPointers() []*Object {
	if m != nil {
		return m.Pointers
	}
	return nil
}

func (m *LogIterator) GetCommits() []*Commit {
	if m != nil {
		return m.Commits
	}
	return nil
}

func init() {
	proto.RegisterType((*Object)(nil), "gitm.protobuf.Object")
	proto.RegisterType((*Repository)(nil), "gitm.protobuf.Repository")
	proto.RegisterType((*Commit)(nil), "gitm.protobuf.Commit")
	proto.RegisterType((*LogIterator)(nil), "gitm.protobuf.LogIterator")
}

func init() { proto.RegisterFile("api/gitm.proto", fileDescriptor_fbd2cb2805ec62ec) }

var fileDescriptor_fbd2cb2805ec62ec = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xad, 0x95, 0xaa, 0xb3, 0xea, 0x61, 0x40, 0xa8, 0x8b, 0x60, 0xcd, 0xc9, 0x8b, 0x2d,
	0xae, 0x27, 0x4f, 0x82, 0x82, 0x20, 0x08, 0x42, 0x8e, 0xde, 0x92, 0x25, 0xb6, 0x11, 0xda, 0x84,
	0x64, 0x16, 0xf1, 0x3b, 0xf9, 0x21, 0xcd, 0xa6, 0xdb, 0xdd, 0x75, 0xf1, 0xcf, 0x6d, 0xe0, 0xfd,
	0xf2, 0xde, 0x9b, 0x0c, 0x1c, 0x09, 0xab, 0xab, 0x5a, 0x53, 0x5b, 0x5a, 0x67, 0xc8, 0xe0, 0xe1,
	0x6a, 0x96, 0xb3, 0x57, 0x76, 0x0a, 0xd9, 0xb3, 0x7c, 0x53, 0x53, 0x42, 0x84, 0x9d, 0x46, 0xf8,
	0x26, 0x4f, 0x8a, 0xe4, 0xe2, 0x80, 0xc7, 0x99, 0x15, 0x00, 0x5c, 0x59, 0xe3, 0x35, 0x19, 0xf7,
	0x31, 0x27, 0xac, 0xa0, 0x9e, 0xd8, 0xe7, 0x71, 0x66, 0x0d, 0x64, 0xf7, 0xa6, 0x6d, 0x35, 0xe1,
	0x25, 0x64, 0x26, 0x3a, 0x45, 0x7d, 0x34, 0x39, 0x2e, 0xbf, 0x25, 0x95, 0x7d, 0x0c, 0x5f, 0x40,
	0x58, 0xc1, 0xae, 0x15, 0x4e, 0x75, 0xe4, 0xf3, 0xed, 0x22, 0xfd, 0x9d, 0x1f, 0x28, 0xf6, 0x99,
	0xc0, 0xe8, 0xc9, 0xd4, 0x8f, 0xa4, 0x9c, 0x08, 0x75, 0xf0, 0x06, 0xc0, 0x2d, 0xbb, 0x2d, 0x32,
	0x4f, 0x36, 0x3c, 0x56, 0xe5, 0xf9, 0x1a, 0x8c, 0x57, 0xb0, 0x67, 0x8d, 0xee, 0x82, 0xd3, 0x3f,
	0xe1, 0x4b, 0x6c, 0x5e, 0x77, 0x1a, 0xf7, 0xf4, 0x79, 0xfa, 0xe3, 0x8b, 0xfe, 0x17, 0xf8, 0x40,
	0x4d, 0x1e, 0x20, 0x0d, 0x6d, 0xf1, 0x16, 0xd2, 0x5a, 0x11, 0x8e, 0x37, 0xe8, 0xb5, 0x45, 0xc6,
	0x7f, 0x68, 0x6c, 0xeb, 0xee, 0xfc, 0xe5, 0x2c, 0xc8, 0xcd, 0x4c, 0x96, 0xc1, 0xb9, 0x7a, 0x17,
	0x9d, 0x90, 0x2a, 0xde, 0xb3, 0x1a, 0x0e, 0x2b, 0xb3, 0xf8, 0xf4, 0xfa, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0xf1, 0x11, 0x5b, 0x20, 0xeb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogClient interface {
	Get(ctx context.Context, in *LogIterator, opts ...grpc.CallOption) (*LogIterator, error)
}

type logClient struct {
	cc *grpc.ClientConn
}

func NewLogClient(cc *grpc.ClientConn) LogClient {
	return &logClient{cc}
}

func (c *logClient) Get(ctx context.Context, in *LogIterator, opts ...grpc.CallOption) (*LogIterator, error) {
	out := new(LogIterator)
	err := c.cc.Invoke(ctx, "/gitm.protobuf.Log/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServer is the server API for Log service.
type LogServer interface {
	Get(context.Context, *LogIterator) (*LogIterator, error)
}

// UnimplementedLogServer can be embedded to have forward compatible implementations.
type UnimplementedLogServer struct {
}

func (*UnimplementedLogServer) Get(ctx context.Context, req *LogIterator) (*LogIterator, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterLogServer(s *grpc.Server, srv LogServer) {
	s.RegisterService(&_Log_serviceDesc, srv)
}

func _Log_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogIterator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitm.protobuf.Log/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Get(ctx, req.(*LogIterator))
	}
	return interceptor(ctx, in, info, handler)
}

var _Log_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitm.protobuf.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _Log_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/gitm.proto",
}
